[build]
  publish = "dist/spa"
  command = "npm run build:client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000